name: Auto Deploy In VPS After Push It Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Repo
        uses: "actions/checkout@v2"
        with:
          ref: main

      - name: Download Decencies
        run: |
          npm ci

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/mobin
            rm -rf frontend
            mkdir frontend
            cd frontend
            git clone https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/mobinrayhan/personal-portfolio.git .
            rm -rf .git 
            rm -rf .github
            npm ci
            npm run build
            npm start
            ls -la
