name: Auto Deploy In VPS After Push It Production
on:
  push:
    branches:
      - main
jobs:
  upload_files:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Repo
        uses: "actions/checkout@v2"
        with:
          ref: main

      # - name: Download Decencies
      #   run: |
      #     npm ci

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/mobin
            rm -rf frontend
            mkdir frontend
            cd frontend
            git clone https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/mobinrayhan/personal-portfolio.git .

            export PATH=/usr/local/bin:$PATH

            # Verify Node.js and npm versions for debugging
            node -v
            npm -v

            # Install dependencies and build the project
            npm install
            npm run build
  # Deploy:
  #   runs-on: ubuntu-latest
  #   needs: upload_files
  #   steps:
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "20"
  #     - name: Build Next JS Project
  #       run: |
  #         cd /www/wwwroot/mobin
  #         npm ci
  #         npm run build
  #         npm start
  #         ls -la
  # rm -rf .git
  # rm -rf .github
  # npm ci
  # npm --version
  # npm run build
  # npm start
