name: Auto Deploy In VPS After Push It Production
on:
  push:
    branches:
      - main
jobs:
  print_hello_world:
    name: Print Hello world
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: "echo Hello world from personal mobin web"
      - name: Print All Env
        run: |
          echo PERSONAL_GITHUB_TOKEN = ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          echo SSH_PRIVATE_KEY = ${{ secrets.SSH_PRIVATE_KEY }}
          echo VPS_IP = ${{ secrets.VPS_IP }}
          echo VPS_USERNAME = ${{ secrets.VPS_USERNAME }}
