name: Auto Deploy In VPS After Push It Production
on:
  push:
    branches:
      - main
jobs:
  upload_files:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Repo
        uses: "actions/checkout@v2"
        with:
          ref: main

      # - name: Download Decencies
      #   run: |
      #     npm ci

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Creating 'frontend' directory..."
            mkdir frontend
            cd frontend

            git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/mobinrayhan/personal-portfolio.git .

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 22
            nvm use 22

            npm ci
            npm run build
            npm run start
            rm -rf .github/
            rm -rf .git/

  # Deploy:
  # Deploy:
  #   runs-on: ubuntu-latest
  #   needs: upload_files
  #   steps:
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "20"
  #     - name: Build Next JS Project
  #       run: |
  #         cd /www/wwwroot/mobin
  #         npm ci
  #         npm run build
  #         npm start
  #         ls -la
  # rm -rf .git
  # rm -rf .github
  # npm ci
  # npm --version
  # npm run build
  # npm start
