name: Auto Deploy In VPS After Push It Production
on:
  push:
    branches:
      - main
jobs:
  print_hello_world:
    name: Print Hello world
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH private key length
        run: |
          echo "SSH_PRIVATE_KEY_LENGTH=$(echo -n "${{ secrets.SSH_PRIVATE_KEY }}" | wc -c)"

      - name: Set up SSH Key and See All Vps Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/soundei/frontend
            ls -la
