name: Auto Deploy In VPS After Push It Production
on:
  push:
    branches:
      - main
jobs:
  upload_files:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out Repo
        uses: "actions/checkout@v2"
        with:
          ref: main

      # - name: Download Decencies
      #   run: |
      #     npm ci

      - name: Deploy and build project on VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          # Navigate to project directory
          cd /www/www***/mobin
    
          # Clean up old files and create a new directory
          rm -rf frontend
          mkdir frontend
          cd frontend
    
          # Clone the repository
          git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/mobinrayhan/personal-portfolio.git .
    
          # Check if Node.js and npm are installed
          if ! command -v node &> /dev/null; then
            echo "Node.js not found. Installing..."
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            source ~/.bashrc
            nvm install --lts
          fi
    
          # Ensure npm is in PATH
          export PATH=$PATH:/usr/local/bin
    
          # Install dependencies and build the project
          npm install
          npm run build
    

  # Deploy:
  #   runs-on: ubuntu-latest
  #   needs: upload_files
  #   steps:
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "20"
  #     - name: Build Next JS Project
  #       run: |
  #         cd /www/wwwroot/mobin
  #         npm ci
  #         npm run build
  #         npm start
  #         ls -la
  # rm -rf .git
  # rm -rf .github
  # npm ci
  # npm --version
  # npm run build
  # npm start
